# Generated by Django 4.1.4 on 2023-02-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_comment_receiver_name_comment_sender_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='sender_name',
        ),
    ]
